Task 7 - Add/Edit/Delete movie with Formik
apyd/Movies-app pull request #5
Opened 2022-07-04 21:11 UTC by apyd

2022-07-10 20:37 UTC, Vladlan requested changes
The task is not ready. Please review requirements and add changes. Also address comments from Task 6. Only after approve of task 7 and merge start Task 8 to make review clean (see only changes related to the task and entire app).

2022-07-10 20:37 UTC, Vladlan commented on src/components/App/App.tsx
> +  const cx = classNames.bind(styles);
Move const cx = classNames.bind(styles); out of the component scope

2022-07-10 20:37 UTC, Vladlan commented on src/components/Footer/Footer.tsx
> +  const cx = classNames.bind(styles);
the same here

2022-07-10 20:37 UTC, Vladlan commented on src/store/api/apiTypes.ts
> +export interface Movie {
movie.interface.ts

2022-07-10 20:48 UTC, Vladlan commented on src/components/Modal/MovieForm/configuration.ts
> +      /((https?):\/\/)?(www.)?[a-z0-9]+(\.[a-z]{2,}){1,3}(#?\/?[a-zA-Z0-9#]+)*\/?(\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+&?)?$/,
Remove www from validation

2022-07-11 19:27 UTC, apyd commented
Comment with pending changes to be done from previous PR: https://github.com/apyd/Movies-app/pull/4#issuecomment-1173709872

2022-07-28 16:30 UTC, Vladlan requested changes
Please fix React red warning:

![Screenshot 2022-07-28 at 18 28 35](https://user-images.githubusercontent.com/20605638/181590122-5d8ab87c-1c36-487e-b532-dd84d432ae36.png)

2022-08-01 16:06 UTC, Vladlan approved these changes

2022-08-01 18:05 UTC, merged